### ISSUE TITLE
Multiple logins with immediate logouts

### ISSUE THREAD

**Issue by abaxx-tech** [abhi-g80/pytradesimulator#1]
Hello
# I am seeing this issue i connect one time and get multiple logins for the one client

2020-09-23 15:03:40.555417 [INFO   ] (onCreate ) Successfully created session FIX.4.4:CLIENT2->EXCHANGE.
2020-09-23 15:03:40.555417 [INFO   ] (onCreate ) Successfully created session FIX.4.4:CLIENT2->EXCHANGE.
2020-09-23 15:03:40.555417 [INFO   ] (onCreate ) Successfully created session FIX.4.4:CLIENT2->EXCHANGE.
2020-09-23 15:03:40.560153 [INFO   ] (onLogon  ) FIX.4.4:EXCHANGE->CLIENT2 session successfully logged in.
2020-09-23 15:03:40.560250 [INFO   ] (onLogon  ) FIX.4.4:CLIENT2->EXCHANGE session successfully logged in.
2020-09-23 15:03:40.560250 [INFO   ] (onLogon  ) FIX.4.4:CLIENT2->EXCHANGE session successfully logged in.
2020-09-23 15:03:40.560250 [INFO   ] (onLogon  ) FIX.4.4:CLIENT2->EXCHANGE session successfully logged in.

-> I send a FIX Message

# Then get multiple logouts 

2020-09-23 15:03:42.567368 [INFO   ] (onLogout ) FIX.4.4:EXCHANGE->CLIENT2 session successfully logged out.
2020-09-23 15:03:42.567521 [INFO   ] (onLogout ) FIX.4.4:CLIENT2->EXCHANGE session successfully logged out.
2020-09-23 15:03:42.567521 [INFO   ] (onLogout ) FIX.4.4:CLIENT2->EXCHANGE session successfully logged out.
2020-09-23 15:03:42.567521 [INFO   ] (onLogout ) FIX.4.4:CLIENT2->EXCHANGE session successfully logged out.

# Is there some trick to maintaining the session_id = fix.SessionID("FIX.4.4", sender_compid, target_compid)

would love some help on this issue - willing to $

**Comment by abhi-g80** [comment]
I am not familiar with FIX 4.4 API and this package was developed with FIX 4.2 in mind. Could you share your exchange and client configuration file ?

**Comment by abaxx-tech** [comment]
**I am not having any issues between 4.2 and 4.4 thats just a spec file - any help you can provide on session / orderbook handling would be extremely helpful**


**In order to not require cfg files in my service -- I am dynamically creating the client configuration like this -** 

    settings = fix.SessionSettings()

    default = fix.Dictionary()
    default.setString("ConnectionType","initiator")
    default.setString("ReconnectInterval", "2")
    default.setString("FileStorePath","store")
    default.setString("FileLogPath","logs")
    default.setString("StartTime","00:00:00")
    default.setString("EndTime","00:00:00")
    default.setString("UseDataDictionary","Y")
    default.setString("DataDictionary","./spec/FIX44.xml")
    default.setString("TimestampPrecision","6")
    default.setString("PreserveMessageFieldsOrder","N")
    settings.set(default);

    session = fix.Dictionary()
    session.setString("BeginString","FIX.4.4")
    session.setString("SenderCompID",msg['sender_comp_id'])
    session.setString("TargetCompID","EXCHANGE")
    session.setString("SocketConnectHost","127.0.0.1")
    session.setString("SocketConnectPort","5001")
    session.setString("HeartBtInt","30")

    session_id = fix.SessionID("FIX.4.4", msg['sender_comp_id'], "EXCHANGE")
    settings.set(session_id, session)
    
    session_settings = settings.get(session_id)
    sender_compid = session_settings.getString('SenderCompID')
    target_compid = session_settings.getString('TargetCompID')

**and the exchange configuration like this**

    settings = fix.SessionSettings()

    default = fix.Dictionary()
    default.setString("ConnectionType","acceptor")
    default.setString("SocketAcceptPort", "5001")
    default.setString("SocketReuseAddress","Y")
    default.setString("StartTime","00:00:00")
    default.setString("EndTime","00:00:00")
    default.setString("SSLProtocol","all")
    default.setString("TimestampPrecision","6")
    default.setString("PreserveMessageFieldsOrder","N")
    default.setString("PersistMessages","N")
    default.setString("FileLogPath","logs")
    default.setString("FileLogEvents","N")
    default.setString("FileLogShowIncoming","N")
    default.setString("FileLogShowOutgoing","N")
    default.setString("FileLogShowHeartBeats","N")
    default.setString("FileStorePath","store")    
    default.setString("ScreenLogEvents","N")
    default.setString("ScreenLogShowIncoming","N")
    default.setString("ScreenLogShowOutgoing","N")
    default.setString("ScreenLogShowHeartBeats","N")
    default.setString("DataDictionary","./spec/FIX44.xml")

    settings.set(default);

    session1 = fix.Dictionary()
    session1.setString("BeginString","FIX.4.4")
    session1.setString("SenderCompID","EXCHANGE")
    session1.setString("TargetCompID","CLIENT1")

    session_id1 = fix.SessionID("FIX.4.4", "EXCHANGE", "CLIENT1")
    settings.set(session_id1, session1)

    session2 = fix.Dictionary()
    session2.setString("BeginString","FIX.4.4")
    session2.setString("SenderCompID","EXCHANGE")
    session2.setString("TargetCompID","CLIENT2")

    session_id2 = fix.SessionID("FIX.4.4", "EXCHANGE", "CLIENT2")
    settings.set(session_id2, session2)

    session3 = fix.Dictionary()
    session3.setString("BeginString","FIX.4.4")
    session3.setString("SenderCompID","EXCHANGE")
    session3.setString("TargetCompID","CLIENT3")

    session_id3 = fix.SessionID("FIX.4.4", "EXCHANGE", "CLIENT3")
    settings.set(session_id3, session3)


**I have been able to get a little further - the goal is I want to send fix message to the service from another api 
the messages are received but after a couple of new orders and one match, the sessions seem to be lost somehow and the order book is no longer updated with new orders and I cannot cancel old orders.** 

**I have a function like below that attempts to process the incoming orders**

    def order(message):
      msg = json.loads(message)
      print("order", msg)

    settings = fix.SessionSettings()

    default = fix.Dictionary()
    default.setString("ConnectionType","initiator")
    default.setString("ReconnectInterval", "2")
    default.setString("FileStorePath","store")
    default.setString("FileLogPath","logs")
    default.setString("StartTime","00:00:00")
    default.setString("EndTime","00:00:00")
    default.setString("UseDataDictionary","Y")
    default.setString("DataDictionary","./spec/FIX44.xml")
    default.setString("TimestampPrecision","6")
    default.setString("PreserveMessageFieldsOrder","N")
    settings.set(default);

    session = fix.Dictionary()
    session.setString("BeginString","FIX.4.4")
    session.setString("SenderCompID",msg["sender_comp_id"])
    session.setString("TargetCompID","EXCHANGE")
    session.setString("SocketConnectHost","127.0.0.1")
    session.setString("SocketConnectPort","5001")
    session.setString("HeartBtInt","30")

    session_id = fix.SessionID("FIX.4.4", msg["sender_comp_id"], "EXCHANGE")
    settings.set(session_id, session)
    
    session_settings = settings.get(session_id)
    sender_compid = session_settings.getString("SenderCompID")
    target_compid = session_settings.getString("TargetCompID")
        
    store = fix.FileStoreFactory(settings)
    
    app = Client()

    app.set_logging(logger)

    initiator = fix.SocketInitiator(app, store, settings)

    initiator.start()
    
    sleep(1)

    if (msg["type"] == "new"):
        try:
            sender_compid = str(msg["sender_comp_id"])
            target_compid = "EXCHANGE"
            symbol = str(msg["symbol"])
            quantity = int(msg["quantity"])
            price = float(msg["price"])
            side = str(msg["side"])
            order_type = str(msg["order_type"])
        except ValueError as e:
            print("sorry, invalid input", e)
            return
        else:
            message = Client.new_order(
                sender_compid,
                target_compid,
                symbol,
                quantity,
                price,
                side,
                order_type,
            )        
            Client.send(message)
            # sleep(3)
            # initiator.stop()
            return "sending new order..."

    elif (msg["type"]) == "replace":
        try:
            sender_compid = str(msg["sender_comp_id"])
            target_compid = "EXCHANGE"
            order_id = str(msg["order_id"])
            price = float(msg["price"])
            quantity = int(msg["quantity"])
        except ValueError:
            print("sorry, invalid input", e)
            return
        else:
            message = Client.replace_order(
                sender_compid, 
                target_compid, 
                quantity, 
                price, 
                order_id
            )
            Client.send(message)
            # sleep(3)
            # initiator.stop()
            return "Sending replace order..."

    elif (msg["type"] == "cancel"):
        try:
            sender_compid = str(msg["sender_comp_id"])
            target_compid = "EXCHANGE"
            order_id = str(msg["order_id"])
        except ValueError:
            print("sorry, invalid input", e)
            return
        else:
            message = Client.delete_order(
                sender_compid, 
                target_compid, 
                order_id
            )
            Client.send(message)
            # sleep(3)
            # initiator.stop()
            return "Sending cancel order..."

**Comment by abhi-g80** [comment]
Sorry, should have mentioned earlier, could you also attach the debug FIX logs (with the initial login, order being sent, match and then session being lost.) Would be helpful for investigating.
