### ISSUE TITLE
Why i can not set breakpoints on a fromApp?

### ISSUE THREAD

**Issue by minikiller** [abhi-g80/pytradesimulator#2]
Dear Sir:
I used your project as a test tools for my Fix job. It works very well, but when i want to debug program.I found i can set breakpoints on toapp method but can not get pause on fromapp. It also have stranger situation such as client can not log in . There is no error showed under console. The client login then logout many times. I do not know why. 
I used vscode as my develop IDE. Thansk for your help!

**Comment by abhi-g80** [comment]
Hi, I have been away from this project for quite a while. Is this still an issue ? Let me know and I will have a look. Apologies for the late reply.
